name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker image
        working-directory: server
        run: docker build -t suryathink/taskmaster-backend:latest .

      - name: Push Docker image to Docker Hub
        run: docker push suryathink/taskmaster-backend:latest

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Save PEM key with line breaks and set permissions
          echo "${EC2_KEY}" | sed 's/\\n/\
          /g' > ec2_key.pem
          chmod 400 ec2_key.pem

          # Connect and deploy on EC2
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${EC2_USER}@${EC2_HOST} << EOF
            # Pull Docker image
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            docker pull suryathink/taskmaster-backend:latest

            # Stop and remove the old container if it exists
            docker stop new-container || true
            docker rm new-container || true

            # Run the new container
            docker run -d -p 8000:8000 --name new-container \
              --env-file /home/ubuntu/.env \
              suryathink/taskmaster-backend:latest
          EOF
